language: php
php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-dist --dev

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs

matrix:
  allow_failures:
    - php: hhvm
  
  fast_finish: true
